// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.BusinessPlugin = (function(_super) {

    __extends(BusinessPlugin, _super);

    function BusinessPlugin() {
      return BusinessPlugin.__super__.constructor.apply(this, arguments);
    }

    BusinessPlugin.prototype.init = function() {
      var annotation, _i, _len, _ref, _ref1, _results;
      this.name = 'BusinessPlugin';
      annotation = void 0;
      console.info("Initialize BusinessPlugin");
      _ref = this.lime.annotations;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        annotation = _ref[_i];
        if (annotation.isBookmark() && annotation.resource.value.indexOf("youtube.com") < 0 && ((_ref1 = annotation.relation.value) === 'http://connectme.at/ontology#explicitlyShows' || _ref1 === 'http://connectme.at/ontology#explicitlyMentions' || _ref1 === 'http://connectme.at/ontology#implicitlyShows' || _ref1 === 'http://connectme.at/ontology#implicitlyMentions' || _ref1 === 'http://connectme.at/ontology#hasContent')) {
          _results.push(this.handleAnnotation(annotation));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    BusinessPlugin.prototype.handleAnnotation = function(annotation) {
      var domain, nonConcept, url, widget,
        _this = this;
      nonConcept = annotation.resource.value;
      if (nonConcept.length >= 3) {
        url = annotation.resource.value;
        domain = url.replace('http://', '').replace('https://', '').split(/[/?#]/)[0].replace('www.', '');
      }
      return widget = this.lime.allocateWidgetSpace(this, {
        thumbnail: "img/shop.png",
        title: "" + domain,
        type: "BusinessWidget",
        sortBy: function() {
          return 10000 * annotation.start + annotation.end;
        }
      }, widget.annotation = annotation, jQuery(widget).bind('activate', function(e) {
        return _this.showAbstractInModalWindow(annotation, _this.getModalContainer());
      }), annotation.widgets[this.name] = widget, jQuery(annotation).bind("becomeActive", function(e) {
        return annotation.widgets[_this.name].setActive();
      }), jQuery(annotation).bind("becomeInactive", function(e) {
        return annotation.widgets[_this.name].setInactive();
      }), jQuery(widget).bind("downarrow", function(e) {
        _this.bookingtabsiterator = _this.videotabs.length === _this.bookingtabsiterator + 1 ? 0 : _this.bookingtabsiterator + 1;
        if (_this.bookingtabsiterator === 0) {
          $("#video1").trigger('click');
          $("#video1").addClass('selected');
        }
        if (_this.bookingtabsiterator === 1) {
          $("#video2").trigger('click');
          $("#video2").addClass('selected');
        }
        if (_this.bookingtabsiterator === 2) {
          $("#video3").trigger('click');
          return $("#video3").addClass('selected');
        }
      }), jQuery(widget).bind("uparrow", function(e) {
        _this.bookingtabsiterator = _this.bookingtabsiterator === 0 ? _this.videotabs.length - 1 : _this.bookingtabsiterator - 1;
        $('.videotab.selected').removeClass('selected');
        if (_this.bookingtabsiterator === 0) {
          $("#video1").trigger('click');
          $("#video1").addClass('selected');
        }
        if (_this.bookingtabsiterator === 1) {
          $("#video2").trigger('click');
          $("#video2").addClass('selected');
        }
        if (_this.bookingtabsiterator === 2) {
          $("#video3").trigger('click');
          return $("#video3").addClass('selected');
        }
      }));
    };

    BusinessPlugin.prototype.showAbstractInModalWindow = function(annotation, outputElement) {
      var lime, modalContent, resource, result;
      modalContent = $(outputElement);
      modalContent.css("width", "800px");
      modalContent.css("height", "600px");
      lime = this.lime;
      resource = "";
      resource = annotation.resource.value;
      if (annotation.resource.value.indexOf("webtv.feratel.com") > 0) {
        resource = resource.replace(/\$\$/g, "&");
      }
      console.log(resource);
      result = "<iframe frameborder=\"0\" style=\"height: 600px; width: 800px; position: relative; margin: 0 auto;\" src=\"" + resource + "\">\n<p>Your browser does not support iframes.</p>\n</iframe>";
      return modalContent.append(result);
    };

    return BusinessPlugin;

  })(window.LimePlugin);

}).call(this);
