// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.GeoNamesMapForTVPlugin = (function(_super) {

    __extends(GeoNamesMapForTVPlugin, _super);

    function GeoNamesMapForTVPlugin() {
      return GeoNamesMapForTVPlugin.__super__.constructor.apply(this, arguments);
    }

    GeoNamesMapForTVPlugin.prototype.init = function() {
      var annotation, _i, _len, _ref, _ref1, _results;
      this.name = 'GeoNamesMapForTVPlugin';
      annotation = void 0;
      console.info("Initialize GeoNamesMapForTVPlugin");
      _ref = this.lime.annotations;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        annotation = _ref[_i];
        if (annotation.resource.value.indexOf("sws.geonames.org") > 0 && ((_ref1 = annotation.relation.value) === 'http://connectme.at/ontology#explicitlyShows' || _ref1 === 'http://connectme.at/ontology#explicitlyMentions' || _ref1 === 'http://connectme.at/ontology#implicitlyShows' || _ref1 === 'http://connectme.at/ontology#implicitlyMentions')) {
          _results.push(this.handleAnnotation(annotation));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    GeoNamesMapForTVPlugin.prototype.handleAnnotation = function(annotation) {
      var _this = this;
      return annotation.entityPromise.done(function() {
        var widget;
        widget = _this.lime.allocateWidgetSpace(_this, {
          thumbnail: "img/mapIcon.png",
          title: "" + (annotation.getLabel()) + " Map",
          type: "GeoNamesMapForTVWidget",
          sortBy: function() {
            return 10000 * annotation.start + annotation.end;
          }
        });
        widget.annotation = annotation;
        jQuery(widget).bind('activate', function(e) {
          return _this.showInModalWindow(annotation, _this.getModalContainer());
        });
        annotation.widgets[_this.name] = widget;
        jQuery(annotation).bind("becomeActive", function(e) {
          return annotation.widgets[_this.name].setActive();
        });
        jQuery(annotation).bind("becomeInactive", function(e) {
          return annotation.widgets[_this.name].setInactive();
        });
        jQuery(widget).bind("leftarrow", function(e) {
          _this.geotabsiterator = _this.geotabs.length === _this.geotabsiterator + 1 ? 0 : _this.geotabsiterator + 1;
          if (_this.geotabsiterator === 0) {
            $("#geoMap").trigger('click');
          }
          if (_this.geotabsiterator === 1) {
            $("#geoWeather").trigger('click');
          }
          if (_this.geotabsiterator === 2) {
            $("#geoRout").trigger('click');
          }
          if (_this.geotabsiterator === 3) {
            return $("#geoPanoramio").trigger('click');
          }
        });
        jQuery(widget).bind("rightarrow", function(e) {
          _this.geotabsiterator = _this.geotabsiterator === 0 ? _this.geotabs.length - 1 : _this.geotabsiterator - 1;
          if (_this.geotabsiterator === 0) {
            $("#geoMap").trigger('click');
          }
          if (_this.geotabsiterator === 1) {
            $("#geoWeather").trigger('click');
          }
          if (_this.geotabsiterator === 2) {
            $("#geoRout").trigger('click');
          }
          if (_this.geotabsiterator === 3) {
            return $("#geoPanoramio").trigger('click');
          }
        });
        jQuery(widget).bind("uparrow", function(e) {
          var currentZoom;
          currentZoom = _this.geomap.getZoom();
          return _this.geomap.setZoom(currentZoom + 1);
        });
        return jQuery(widget).bind("downarrow", function(e) {
          var currentZoom;
          currentZoom = _this.geomap.getZoom();
          return _this.geomap.setZoom(currentZoom - 1);
        });
      });
    };

    GeoNamesMapForTVPlugin.prototype.showInModalWindow = function(annotation, outputElement) {
      var language, modalContent, result, startTime,
        _this = this;
      modalContent = void 0;
      result = void 0;
      language = UTILS.getParameterByName("lang");
      startTime = new Date().getTime();
      modalContent = $(outputElement);
      modalContent.css("width", "600px");
      modalContent.css("height", "500px");
      if (language.indexOf("en") >= 0) {
        result = "<div id=\"ifoWidgetExpanded\" style=\"border: 1px dotted lightgray; position: absolute; top: 0; z-index: 100; width: 600px; right: 0; height: 100%;\">\n<img id=\"map_area\" style=\"left: 0px; top: 0px; width: 600px; height: 100%; position: relative;\"></img>\n<div id=\"mapMenu\" style=\"position: absolute; z-index: 900; width: auto; right: 1px; bottom: 0px; height: 41px;\">\n<div id=\"geoMap\" class=\"geotab\" style=\"position: relative; background-position: center center; background-image: url('img/mapIcon.png'); background-size: contain; float: right; height: 40px; width: 86px;\"></div>\n<div id=\"geoWeather\" class=\"geotab\" style=\"position: relative; background-position: center center; background-image: url('img/weather.png'); background-size: contain; float: right; width: 86px; height: 40px;\"></div>\n<div id=\"geoRout\" class=\"geotab disabled\" style=\"display: none; background-position: center center; background-size: contain; background-image: url('img/directionIcon.png'); float: right; width: 86px; height: 40px;\"></div>\n<div id=\"geoPanoramio\" class=\"geotab disabled\" style=\"display: none; background-position: center center; background-size: contain; background-image: url('img/directionIcon.png'); float: right; width: 86px; height: 40px;\"></div>\n</div>\n<!-- <div id=\"closingButton\" style=\"position: absolute; z-index: 900; width: 87px; height: 38px; background-color: #414040; left: 513px; top: 408px;\"><span data-dojo-type=\"shapes.Text\" style=\"font-size: 14px; position: absolute; z-index: 900; color: #ffffff; left: 41px; top: 8.5px;\">X</span></div> -->\n</div>";
      } else {
        result = "<div id=\"ifoWidgetExpanded\" style=\"border: 1px dotted lightgray; position: absolute; top: 0; z-index: 100; width: 600px; right: 0; height: 80%;\">\n<div id=\"map_area\" style=\"left: 0px; top: 0px; width: 600px; height: 100%; position: relative;\"></div>\n<div id=\"mapMenu\" style=\"position: absolute; z-index: 900; width: auto; right: 1px; bottom: 0px; height: 41px;\">\n<div id=\"geoMap\" class=\"geotab\" style=\"position: relative; background-position: center center; background-image: url('img/mapIcon.png'); background-size: contain; float: right; height: 40px; width: 86px;\"></div>\n<div id=\"geoWeather\" class=\"geotab\" style=\"position: relative; background-position: center center; background-image: url('img/weather.png'); background-size: contain; float: right; width: 86px; height: 40px;\"></div>\n<div id=\"geoRout\" class=\"geotab disabled\" style=\"display: none; background-position: center center; background-size: contain; background-image: url('img/directionIcon.png'); float: right; width: 86px; height: 40px;\"></div>\n<div id=\"geoPanoramio\" class=\"geotab disabled\" style=\"display: none; background-position: center center; background-size: contain; background-image: url('img/directionIcon.png'); float: right; width: 86px; height: 40px;\"></div>\n</div>\n<!-- <div id=\"closingButton\" style=\"position: absolute; z-index: 900; width: 87px; height: 38px; background-color: #414040; left: 513px; top: 408px;\"><span data-dojo-type=\"shapes.Text\" style=\"font-size: 14px; position: absolute; z-index: 900; color: #ffffff; left: 41px; top: 8.5px;\">X</span></div> -->\n</div>";
      }
      modalContent.append(result);
      this.geotabs = $('.geotab:not(.disabled)');
      this.geotabsiterator = 0;
      $(".close").click(function(e) {
        var endTime, eventLabel, timeSpent;
        endTime = new Date().getTime();
        timeSpent = endTime - startTime;
        eventLabel = annotation.widgets[_this.name].options.title;
        return console.log(": " + eventLabel + " was viewed " + timeSpent + " msec.");
      });
      $('#mask').click(function(e) {
        var endTime, eventLabel, timeSpent;
        endTime = new Date().getTime();
        timeSpent = endTime - startTime;
        eventLabel = annotation.widgets[_this.name].options.title;
        return console.log(": " + eventLabel + " was viewed " + timeSpent + " msec.");
      });
      $("#geoMap").click(function() {
        var i, latitude, latlng, locationName, longitude, map, mapzoom, myOptions, output;
        $('.geotab.selected').removeClass('selected');
        $("#location_bar").css("visibility", "visible");
        $("#weather_bar").css("visibility", "hidden");
        $("#rout_bar").css("visibility", "hidden");
        $("#map_area").empty();
        i = void 0;
        latitude = void 0;
        latlng = void 0;
        locationName = void 0;
        longitude = void 0;
        map = void 0;
        myOptions = void 0;
        output = void 0;
        locationName = annotation.getLabel();
        latitude = annotation.getLatitude();
        longitude = annotation.getLongitude();
        mapzoom = 12;
        map = "#map_area";
        jQuery(map).attr("src", "http://maps.googleapis.com/maps/api/staticmap?center=" + latitude + "," + longitude + "&zoom=" + mapzoom + "&size=600x500&maptype=roadmap&sensor=true_or_false");
        return $("#geoMap").addClass('selected');
      });
      $("#geoWeather").click(function() {
        var i, latitude, latlng, locationName, longitude, map, mapzoom, myOptions, output, weatherLayer;
        $('.geotab.selected').removeClass('selected');
        $("#location_bar").css("visibility", "hidden");
        $("#weather_bar").css("visibility", "visible");
        $("#rout_bar").css("visibility", "hidden");
        $("#map_area").empty();
        i = void 0;
        latitude = void 0;
        latlng = void 0;
        locationName = void 0;
        longitude = void 0;
        map = void 0;
        myOptions = void 0;
        output = void 0;
        weatherLayer = void 0;
        locationName = annotation.getLabel();
        latitude = annotation.getLatitude();
        longitude = annotation.getLongitude();
        locationName = annotation.getLabel();
        latitude = annotation.getLatitude();
        longitude = annotation.getLongitude();
        mapzoom = 12;
        map = "#map_area";
        jQuery(map).attr("src", "http://maps.googleapis.com/maps/api/staticmap?center=" + latitude + "," + longitude + "&zoom=" + mapzoom + "&size=600x500&maptype=roadmap&sensor=true_or_false");
        return $("#geoWeather").addClass('selected');
      });
      $("#geoRout").click(function() {
        $('.geotab.selected').removeClass('selected');
        $("#location_bar").css("visibility", "hidden");
        $("#weather_bar").css("visibility", "hidden");
        $("#rout_bar").css("visibility", "visible");
        $("#map_area").empty();
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition((function(position) {
            var destination, directionsDisplay, i, latitude, locationName, longitude, map, mapOptions, myOptions, output, request, start;
            i = void 0;
            latitude = void 0;
            locationName = void 0;
            longitude = void 0;
            map = void 0;
            myOptions = void 0;
            output = void 0;
            locationName = annotation.getLabel();
            latitude = annotation.getLatitude();
            longitude = annotation.getLongitude();
            output = document.getElementById("map_area");
            directionsDisplay = new google.maps.DirectionsRenderer();
            destination = new google.maps.LatLng(latitude, longitude);
            mapOptions = {
              zoom: 7,
              mapTypeId: google.maps.MapTypeId.ROADMAP,
              center: destination
            };
            map = new google.maps.Map(output, mapOptions);
            start = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
            directionsDisplay.setMap(map);
            this.geomap = map;
            request = {
              origin: start,
              destination: destination,
              travelMode: google.maps.TravelMode.DRIVING
            };
            return directionsService.route(request, function(result, status) {
              if (status === google.maps.DirectionsStatus.OK) {
                return directionsDisplay.setDirections(result);
              }
            });
          }), function(error) {
            switch (error.code) {
              case error.TIMEOUT:
                return alert("Timeout");
              case error.POSITION_UNAVAILABLE:
                return alert("Position unavailable");
              case error.PERMISSION_DENIED:
                return alert("Permission denied");
              case error.UNKNOWN_ERROR:
                return alert("Unknown error");
            }
          });
        }
        return $("#geoRout").addClass('selected');
      });
      $("#geoPanoramio").click(function() {
        $('.geotab.selected').removeClass('selected');
        return $("#geoPanoramio").addClass('selected');
      });
      $("#geoMap").trigger("click");
      $("#geoMap").addClass('selected');
    };

    return GeoNamesMapForTVPlugin;

  })(window.LimePlugin);

}).call(this);
