// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.GoogleWeatherPlugin = (function(_super) {

    __extends(GoogleWeatherPlugin, _super);

    function GoogleWeatherPlugin() {
      return GoogleWeatherPlugin.__super__.constructor.apply(this, arguments);
    }

    GoogleWeatherPlugin.prototype.init = function() {
      var annotation, _i, _len, _ref,
        _this = this;
      this.name = 'GoogleWeatherPlugin';
      annotation = void 0;
      console.info("Initialize GoogleWeatherPlugin");
      _ref = this.lime.annotations;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        annotation = _ref[_i];
        jQuery(annotation).bind("becomeActive", function(e) {
          annotation = e.target;
          if (annotation.resource.value.indexOf("geonames") > 0 && annotation.resource.value.indexOf("about.rdf") < 0) {
            return annotation.entityPromise.done(function(entity) {
              var domEl;
              domEl = _this.lime.allocateWidgetSpace(_this);
              if (domEl) {
                if (annotation.ldLoaded) {
                  domEl.html(_this.renderAnnotation(annotation));
                  $(domEl).slideDown(500);
                } else {
                  jQuery(annotation).bind("ldloaded", function(e) {
                    annotation = e.target;
                    domEl.html(_this.renderAnnotation(annotation));
                    return $(domEl).slideDown(500);
                  });
                }
                domEl.click(function() {
                  _this.lime.player.pause();
                  return _this.displayModal(annotation);
                });
                return annotation.widgets.DBPediaAbstractPlugin = domEl;
              }
            });
          }
        });
      }
      return jQuery(annotation).bind("becomeInactive", function(e) {
        annotation = e.target;
        if (annotation.widgets.DBPediaAbstractPlugin) {
          annotation.widgets.DBPediaAbstractPlugin.find(".utility-icon").attr("src", "img/weather_gr.png");
          annotation.widgets.DBPediaAbstractPlugin.find(".utility-text").css("color", "#c6c4c4");
        }
      });
    };

    GoogleWeatherPlugin.prototype.renderAnnotation = function(annotation) {
      var city, current_conditions, hasWeather, i, latitude, locationName, longitude, queryString, querystring, returnResult, temp_c, temp_f, weather_condition, weather_icon, x, xmlDoc, xmlhttp;
      hasWeather = false;
      returnResult = "<p> Should be a Weather widget here </p>";
      try {
        if (window.XMLHttpRequest) {
          xmlhttp = new XMLHttpRequest();
        } else {
          xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
        }
        xmlhttp.open("POST", annotation.resource.value + "/about.rdf", false);
        xmlhttp.send();
        xmlDoc = xmlhttp.responseXML;
        queryString = void 0;
        x = xmlDoc.getElementsByTagName("Feature");
        i = 0;
        while (i < x.length) {
          locationName = x[i].getElementsByTagName("name")[0].childNodes[0].nodeValue;
          latitude = x[i].getElementsByTagName("lat")[0].childNodes[0].nodeValue;
          longitude = x[i].getElementsByTagName("long")[0].childNodes[0].nodeValue;
          i++;
        }
        if (locationName !== "") {
          locationName = locationName.replace(" ", "+");
          hasWeather = true;
          querystring = "./backup/" + locationName + ".xml";
          xmlhttp.open("GET", querystring, false);
          xmlhttp.send();
          xmlDoc = xmlhttp.responseXML;
          city = xmlDoc.getElementsByTagName("city")[0].getAttribute("data");
          temp_c = xmlDoc.getElementsByTagName("temp_c")[0].getAttribute("data");
          temp_f = xmlDoc.getElementsByTagName("temp_f")[0].getAttribute("data");
          current_conditions = xmlDoc.getElementsByTagName("current_conditions");
          weather_condition = current_conditions[0].getElementsByTagName("condition")[0].getAttribute("data");
          weather_icon = current_conditions[0].getElementsByTagName("icon")[0].getAttribute("data");
          weather_icon = "http://www.google.com" + weather_icon;
          returnResult = "<div class=\"GoogleWeatherWidget\">" + "<table style=\"margin:0 auto; width: 100%;\">" + "<tr>" + "<td><b class=\"utility-text\" >" + locationName + " Weather </b></td>" + "<td><img class=\"utility-icon\" src=\"img/weather.png\" style=\"float: right; width: 25px; height: 25px; \" ></td>" + "</tr>" + "</table>" + "</div>";
        }
      } catch (_error) {}
      return returnResult;
    };

    GoogleWeatherPlugin.prototype.showWeatherInModalWindow = function(outputElement) {
      var latlng, map, myOptions, output, weatherLayer;
      output = document.getElementById(outputElement);
      latlng = new google.maps.LatLng(latitude, longitude);
      myOptions = {
        zoom: 11,
        center: latlng,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      };
      map = new google.maps.Map(output, myOptions);
      weatherLayer = new google.maps.weather.WeatherLayer({
        temperatureUnits: google.maps.weather.TemperatureUnit.CELSIUS
      });
      return weatherLayer.setMap(map);
    };

    GoogleWeatherPlugin.prototype.displayModal = function(annotation) {
      var mask, maskHeight, maskWidth, modalcontainer, winH, winW,
        _this = this;
      if (this.lime.player.isFullScreen) {
        modalcontainer = $(".modalwindow");
      } else {
        modalcontainer = $("#modalWindow");
      }
      mask = void 0;
      if (this.lime.player.isFullScreen) {
        mask = $(".mask");
      } else {
        mask = $("#mask");
      }
      $(modalcontainer).css("height", "70%");
      $(modalcontainer).css("max-height", "1200px");
      $(modalcontainer).empty();
      $(modalcontainer).append("<a href=\"#\" class=\"close\" role=\"button\"><img src=\"img/close-icon.png\" style=\"width: 22px; height: 22px;\"/></a>");
      $(modalcontainer).append("<div id=\"modalContent\" style=\"height: 95%; width: 100%; position: relative; margin: 0 auto; color: black; \"> &nbsp");
      $(modalcontainer).append("</div>");
      maskHeight = $(window).height();
      maskWidth = $(window).width();
      $(mask).css({
        width: maskWidth,
        height: maskHeight
      });
      $(mask).fadeIn(100);
      $(mask).fadeTo("fast", 0.8);
      winH = $(window).height();
      winW = $(window).width();
      $(modalcontainer).css("top", winH / 2 - $(modalcontainer).height() / 2);
      $(modalcontainer).css("left", winW / 2 - $(modalcontainer).width() / 2);
      $(modalcontainer).fadeIn(100);
      $(".close").click(function(e) {
        e.preventDefault();
        $(mask).hide();
        return $(modalcontainer).hide();
      });
      $(mask).click(function(e) {
        $(_this).hide();
        return $(modalcontainer).hide();
      });
      $(window).resize(function(e) {
        maskHeight = $(document).height();
        maskWidth = $(document).width();
        $(mask).css({
          width: maskWidth,
          height: maskHeight
        });
        winH = $(window).height();
        winW = $(window).width();
        $(modalcontainer).css("top", winH / 2 - $(modalcontainer).height() / 2);
        return $(modalcontainer).css("left", winW / 2 - $(modalcontainer).width() / 2);
      });
      return showWeatherInModalWindow("modalContent");
    };

    return GoogleWeatherPlugin;

  })(window.LimePlugin);

}).call(this);
