// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.UserSettingsPlugin = (function(_super) {

    __extends(UserSettingsPlugin, _super);

    function UserSettingsPlugin() {
      return UserSettingsPlugin.__super__.constructor.apply(this, arguments);
    }

    UserSettingsPlugin.prototype.init = function() {
      var _this = this;
      this.name = 'UserSettingsPlugin';
      console.info("Initialize " + this.name);
      return this.lime.player.bind('pause', function(e) {
        return console.info('getAllTypes', _this.getAllTypes());
      });
    };

    UserSettingsPlugin.prototype.defaults = {
      unhidable: []
    };

    UserSettingsPlugin.prototype.getAllTypes = function() {
      var res;
      res = _(this.lime.widgets).chain().map(function(widget) {
        return widget.options.type;
      }).uniq().sort().value();
      return res;
    };

    return UserSettingsPlugin;

  })(window.LimePlugin);

}).call(this);
