// Generated by CoffeeScript 1.3.3
(function() {
  var RDF,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.LDPlugin = (function(_super) {

    __extends(LDPlugin, _super);

    function LDPlugin() {
      return LDPlugin.__super__.constructor.apply(this, arguments);
    }

    LDPlugin.prototype.init = function() {
      var annotation, _i, _len, _ref, _results;
      this.vie = this.lime.options.vie || this.options.vie;
      if (!this.vie) {
        if (this.lime.options.local) {
          jQuery.noop();
        }
        this.vie = new VIE();
        this.vie.use(new this.vie.StanbolService({
          url: this.options.stanbolUrl
        }));
      }
      _ref = this.lime.annotations;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        annotation = _ref[_i];
        _results.push(this.loadAnnotation(annotation));
      }
      return _results;
    };

    LDPlugin.prototype.defaults = {
      stanbolUrl: "http://dev.iks-project.eu/stanbolfull"
    };

    LDPlugin.prototype.loadAnnotation = function(annotation) {
      var entityUri, error, requestUrl,
        _this = this;
      annotation.entityPromise = jQuery.Deferred();
      entityUri = annotation.resource.value;
      error = function(err) {
        return console.error("Couldn't load entity " + entityUri, err);
      };
      this.vie.load({
        entity: entityUri
      }).using('stanbol').execute().fail(error).success(function(res) {
        annotation.entity = _.detect(res, function(ent) {
          return ent.fromReference(ent.getSubject()) === entityUri;
        });
        console.info(annotation.entity, res);
        annotation.getLabel = function() {
          return VIE.Util.getPreferredLangForPreferredProperty(annotation.entity, ['rdfs:label'], [_this.lime.options.preferredLanguage, 'en']);
        };
        annotation.getDescription = function() {
          return VIE.Util.getPreferredLangForPreferredProperty(annotation.entity, ['dbpedia:abstract'], [_this.lime.options.preferredLanguage, 'en']);
        };
        annotation.getDepiction = function() {
          var depiction, singleDepiction;
          depiction = annotation.entity.get('foaf:depiction');
          if (_.isArray(depiction)) {
            singleDepiction = _.detect(depiction, function(d) {
              return d.indexOf('thumb') !== -1;
            });
            if (!singleDepiction) {
              singleDepiction = depiction[0];
            }
          } else {
            singleDepiction = depiction;
          }
          return annotation.entity.fromReference(singleDepiction);
        };
        return annotation.getPage = function() {
          return annotation.entity.get('foaf:homepage') || annotation.entity.fromReference(annotation.entity.getSubject());
        };
      });
      return;
      requestUrl = "" + this.lime.options.annotFrameworkURL + "meta/application/json?uri=" + (encodeURIComponent(annotation.resource.value));
      return jQuery.ajax({
        url: requestUrl,
        timeout: 2000,
        success: function(res) {
          var lime;
          if (typeof res === 'string') {
            res = JSON.parse(res);
          }
          if (_.keys(res).length) {
            console.info(annotation.resource.value, res);
            lime = _this.lime;
            annotation.getLabel = function() {
              var label;
              label = _(this.entity['rdfs:label']).detect(function(labelObj) {
                return labelObj["@language"] === lime.options.preferredLanguage;
              });
              if (!label) {
                label = _(this.entity['rdfs:label']).detect(function(labelObj) {
                  return labelObj["@language"] === "en";
                });
                if (label) {
                  return label["@value"] + " (Not found in " + lime.options.preferredLanguage.toUpperCase() + ")";
                }
              }
              return (label != null ? label["@value"] : void 0) || "No label found";
            };
            annotation.getDescription = function() {
              var label;
              label = _(this.entity['http://dbpedia.org/ontology/abstract']).detect(function(labelObj) {
                return labelObj["@language"] === lime.options.preferredLanguage;
              });
              if (!label) {
                label = _(this.entity['http://dbpedia.org/ontology/abstract']).detect(function(labelObj) {
                  return labelObj["@language"] === "en";
                });
                if (label) {
                  label["@value"] += " (Not found in " + lime.options.preferredLanguage.toUpperCase() + ")";
                }
              }
              return label = (label != null ? label["@value"] : void 0) || "No label found";
            };
            annotation.getDepiction = function() {
              var depiction, _ref;
              depiction = (_ref = this.entity['foaf:depiction']) != null ? _ref["@id"] : void 0;
              return depiction;
            };
            annotation.getPage = function() {
              var page, _ref;
              page = (_ref = this.entity['http://xmlns.com/foaf/0.1/homepage']) != null ? _ref["@id"] : void 0;
              return page;
            };
            annotation.entity = res;
            annotation.ldLoaded = true;
            return jQuery(annotation).trigger(jQuery.Event("ldloaded", {
              entity: res
            }));
          }
        },
        error: function(jqXhr, message) {
          alert("Linked data plugin couldn't load the entity because of '" + message + "'");
          return console.error("LDPlugin error", message);
        }
      });
    };

    return LDPlugin;

  })(window.LimePlugin);

  RDF = (function() {

    function RDF(hash) {}

    return RDF;

  })();

}).call(this);
