// Generated by CoffeeScript 1.3.3
(function() {
    var __hasProp = {}.hasOwnProperty,
        __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

    window.HelpPlugin = (function(_super) {

        __extends(HelpPlugin, _super);

        function HelpPlugin() {
            return HelpPlugin.__super__.constructor.apply(this, arguments);
        }

        HelpPlugin.prototype.init = function() {
            var annotation,
                _this = this;
            this.name = 'HelpPlugin';
            annotation = void 0;
            console.info("Initialize HelpPlugin");
            return $("div .help").click(function() {
                _this.lime.player.pause();
                return _this.renderHelpInModalWindow( _this.getModalContainer());
            });
        };

        HelpPlugin.prototype.renderHelpInModalWindow = function(outputElement) {
            var modalContent, result;
            modalContent = $(outputElement);
            modalContent.css("width", "598px");
            modalContent.css("height", "326px");
            result = "<div class=\"statistic\" style=\"margin:0 auto; width: 100%; height: 100%; background-repeat: no-repeat; background-position: center center; background-size: contain; background-image: url('img/helpMC.png');\"> </div>";

            return modalContent.append(result);
        };

        HelpPlugin.prototype.displayStatisticsInModal = function() {
            var mask, maskHeight, maskWidth, modalcontainer, winH, winW,
                _this = this;
            if (this.lime.player.isFullScreen) {
                modalcontainer = $(".modalwindow");
            } else {
                modalcontainer = $("#modalWindow");
            }
            mask = void 0;
            if (this.lime.player.isFullScreen) {
                mask = $(".mask");
            } else {
                mask = $("#mask");
            }
            $(modalcontainer).css("height", "70%");
            $(modalcontainer).css("max-height", "1200px");
            $(modalcontainer).empty();
            $(modalcontainer).append("<a href=\"#\" class=\"close\" role=\"button\"><img src=\"img/close-icon.png\" style=\"width: 22px; height: 22px;\"/></a>");
            $(modalcontainer).append("<div id=\"modalContent\" style=\"height: 95%; width: 100%; position: relative; margin: 0 auto; color: black; \"> &nbsp");
            $(modalcontainer).append("</div>");
            maskHeight = $(window).height();
            maskWidth = $(window).width();
            $(mask).css({
                width: maskWidth,
                height: maskHeight
            });
            $(mask).fadeIn(100);
            $(mask).fadeTo("fast", 0.8);
            winH = $(window).height();
            winW = $(window).width();
            $(modalcontainer).css("top", winH / 2 - $(modalcontainer).height() / 2);
            $(modalcontainer).css("left", winW / 2 - $(modalcontainer).width() / 2);
            $(modalcontainer).fadeIn(100);
            $(".close").click(function(e) {
                e.preventDefault();
                $(mask).hide();
                return $(modalcontainer).hide();
            });
            $(mask).click(function(e) {
                $(mask).hide();
                $(modalcontainer).hide();
                return $(modalcontainer).empty();
            });
            $(window).resize(function(e) {
                maskHeight = $(document).height();
                maskWidth = $(document).width();
                $(mask).css({
                    width: maskWidth,
                    height: maskHeight
                });
                winH = $(window).height();
                winW = $(window).width();
                $(modalcontainer).css("top", winH / 2 - $(modalcontainer).height() / 2);
                return $(modalcontainer).css("left", winW / 2 - $(modalcontainer).width() / 2);
            });
            return this.renderStatisticsInModalWindow();
        };

        return HelpPlugin;

    })(window.LimePlugin);

}).call(this);
