// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.UserSettingsPlugin = (function(_super) {

    __extends(UserSettingsPlugin, _super);

    function UserSettingsPlugin() {
      return UserSettingsPlugin.__super__.constructor.apply(this, arguments);
    }

    UserSettingsPlugin.prototype.init = function() {
      var annotation,
        _this = this;
      this.name = 'UserSettingsPlugin';
      annotation = void 0;
      console.info("Initialize UserSettingsPlugin");
      return $("div .usersettings").click(function() {
        _this.lime.player.pause();
        return _this.displayUserSettingsInModal();
      });
    };

    UserSettingsPlugin.prototype.renderUserSettingsInModalWindow = function() {
      var hasDBPediaInfoPlugin, hasGeoNamesMapPlugin, hasGoogleWeatherPlugin, hasLSIImagePlugin, hasLSIVideoPlugin, modalContent, result;
      hasGeoNamesMapPlugin = this.lime.options.plugins.hasOwnProperty("GeoNamesMapPlugin") ? "checked" : " ";
      hasGoogleWeatherPlugin = this.lime.options.plugins.hasOwnProperty("GoogleWeatherPlugin") ? "checked" : " ";
      hasDBPediaInfoPlugin = this.lime.options.plugins.hasOwnProperty("DBPediaInfoPlugin") ? "checked" : " ";
      hasLSIImagePlugin = this.lime.options.plugins.hasOwnProperty("LSIImagePlugin") ? "checked" : " ";
      hasLSIVideoPlugin = this.lime.options.plugins.hasOwnProperty("LSIVideoPlugin") ? "checked" : " ";
      console.log("hasGeoNamesMapPlugin " + hasGeoNamesMapPlugin);
      console.log("hasGoogleWeatherPlugin " + hasGoogleWeatherPlugin);
      console.log("hasDBPediaInfoPlugin " + hasDBPediaInfoPlugin);
      console.log("hasLSIImagePlugin " + hasLSIImagePlugin);
      result = "<div class=\"settingscontent\" style=\"color: white;\">\n<p class=\"settingstitle\" style=\"font-size: 20px; \"> Video Settings </p>\n<p class=\"settingssection\" style=\"font-size: 16px; \"> Annotations </p>\n<div style=\"margin: 0 auto; width: 75%;\">\n<form style=\"margin: 0 auto; text-align: center; font-size: 14px;\">\n<input type=\"checkbox\" class=\"annotationspatialoverlay \" checked=\"checked\"> Show annotation overlays on the video &nbsp; &nbsp; &nbsp;\n<input type=\"checkbox\" class=\"annotationtimelineoverlay setting\" checked=\"checked\"> Show annotation overlays on the timeline\n</form>\n</div>\n<br>\n<p class=\"settingssection\" style=\"font-size: 16px; \"> Widgets </p>\n<div style=\"margin: 0 auto; width: 50%;\">\n<form style=\"margin: 0 auto; text-align: left; font-size: 14px; margin-left: 45%;\" >\n<div><input type=\"checkbox\" class=\"informationwidgets setting\" " + hasDBPediaInfoPlugin + "> Show information widgets  </div>\n<div><input type=\"checkbox\" class=\"picturewidgets setting\" " + hasLSIImagePlugin + "> Show picture widgets  </div>\n<div><input type=\"checkbox\" class=\"mapwidgets setting\" " + hasGeoNamesMapPlugin + " > Show map widgets  </div>\n<div><input type=\"checkbox\" class=\"weatherwidgets setting\" " + hasGoogleWeatherPlugin + "> Show weather widgets  </div>\n<div><input type=\"checkbox\" class=\"videowidgets setting\" " + hasLSIVideoPlugin + "> Show video widgets</div>\n</form>\n</div>\n</div>";
      modalContent = $("#modalContent");
      modalContent.css('overflow', 'auto');
      return modalContent.append(result);
    };

    UserSettingsPlugin.prototype.displayUserSettingsInModal = function() {
      var mask, maskHeight, maskWidth, modalcontainer, winH, winW,
        _this = this;
      if (this.lime.player.isFullScreen) {
        modalcontainer = $(".modalwindow");
      } else {
        modalcontainer = $("#modalWindow");
      }
      mask = void 0;
      if (this.lime.player.isFullScreen) {
        mask = $(".mask");
      } else {
        mask = $("#mask");
      }
      $(modalcontainer).css("height", "70%");
      $(modalcontainer).css("max-height", "1200px");
      $(modalcontainer).empty();
      $(modalcontainer).append("<a href=\"#\" class=\"close\" role=\"button\"><img src=\"img/close-icon.png\" style=\"width: 22px; height: 22px;\"/></a>");
      $(modalcontainer).append("<div id=\"modalContent\" style=\"height: 95%; width: 100%; position: relative; margin: 0 auto; color: black; \"> &nbsp");
      $(modalcontainer).append("</div>");
      maskHeight = $(window).height();
      maskWidth = $(window).width();
      $(mask).css({
        width: maskWidth,
        height: maskHeight
      });
      $(mask).fadeIn(100);
      $(mask).fadeTo("fast", 0.8);
      winH = $(window).height();
      winW = $(window).width();
      $(modalcontainer).css("top", winH / 2 - $(modalcontainer).height() / 2);
      $(modalcontainer).css("left", winW / 2 - $(modalcontainer).width() / 2);
      $(modalcontainer).fadeIn(100);
      $(".close").click(function(e) {
        e.preventDefault();
        $(mask).hide();
        return $(modalcontainer).hide();
      });
      $(mask).click(function(e) {
        $(mask).hide();
        $(modalcontainer).hide();
        return $(modalcontainer).empty();
      });
      $(window).resize(function(e) {
        maskHeight = $(document).height();
        maskWidth = $(document).width();
        $(mask).css({
          width: maskWidth,
          height: maskHeight
        });
        winH = $(window).height();
        winW = $(window).width();
        $(modalcontainer).css("top", winH / 2 - $(modalcontainer).height() / 2);
        return $(modalcontainer).css("left", winW / 2 - $(modalcontainer).width() / 2);
      });
      return this.renderUserSettingsInModalWindow();
    };

    return UserSettingsPlugin;

  })(window.LimePlugin);

}).call(this);
